In [1]:
import pickle 
import torch
import numpy as np
import torch.nn as nn 
import torch.nn.functional as F

from data_generators import batches_generator, transaction_features
from models import TransactionsRnn, TransactionsModel

from augmentations import add_noise

In [2]:
path_to_dataset = '../train_buckets'
dir_with_datasets = os.listdir(path_to_dataset)
dataset_train = sorted([os.path.join(path_to_dataset, x) for x in dir_with_datasets])

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [3]:
train_generator = batches_generator(dataset_train, batch_size=128, shuffle=True,
                                    device=device, is_train=True, output_format='torch')

In [5]:
b = next(iter(train_generator))

In [15]:
b['transactions_features']

[tensor([[1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         ...,
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0]], device='cuda:0'),
 tensor([[1, 1, 1,  ..., 0, 0, 0],
         [2, 2, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         ...,
         [1, 1, 1,  ..., 0, 0, 0],
         [4, 4, 4,  ..., 0, 0, 0],
         [1, 4, 1,  ..., 0, 0, 0]], device='cuda:0'),
 tensor([[  1,   1,   1,  ...,   0,   0,   0],
         [  3,   3,   3,  ...,   0,   0,   0],
         [  2,   2,   2,  ...,   0,   0,   0],
         ...,
         [ 98,  98,  98,  ...,   0,   0,   0],
         [ 67,  67,  67,  ...,   0,   0,   0],
         [110, 110, 110,  ...,   0,   0,   0]], device='cuda:0'),
 tensor([[1, 1, 1,  ..., 0, 0, 0],
         [8, 8, 9,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         ...,
         [1, 1, 1,  ..., 0, 0, 0],
         [4, 4, 4,  ..., 0, 0, 0],
         [

In [5]:
with open('./assets/embedding_projections.pkl', 'rb') as f:
    embedding_projections = pickle.load(f)

In [6]:
ckpt = torch.load('/datasets/home/andrey/al/romashka/wandb/run-20221101_224414-1hiz5uxa/checkpoints/epoch_9.ckpt')
model = TransactionsRnn(transaction_features, embedding_projections)
model.load_state_dict(ckpt)
model.to(device);

In [8]:
ckpt = torch.load('/datasets/home/andrey/al/romashka/wandb/run-20221102_131548-3v39ss2u/checkpoints/epoch_0.ckpt')

new_dict = {}
for key in ckpt:
    new_dict[key[6:]] = ckpt[key]

m = TransactionsModel(transaction_features, embedding_projections, head_type='id')
m.load_state_dict(new_dict)

USING rel_pos_embs=False
